[package]
name = "basic_token_actor"
version = "0.1.0"
repository = "https://github.com/helix-collective/filecoin"
edition = "2021"
publish = false

[dependencies]
frc46_token = { path = "../../../../frc46_token" }
fvm_actor_utils = { path = "../../../../fvm_actor_utils" }

cid = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_sdk = { workspace = true }
fvm_shared = { workspace = true }
num-traits = { version = "0.2.15" }
serde = { version = "1.0.136", features = ["derive"] }
thiserror = { version = "1.0.31" }

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build
