name: Check Main Builds

on:
  push:
    branches:
      - main

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make check-build
