name: Rust code checks

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Formatting
        run: cargo fmt --check

      - name: Linting
        run: cargo clippy --all-targets --all-features
