name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make check-build
  actor-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Actors
        run: make test-actors
  code-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Installing Cargo llvm-cov
      uses: taiki-e/install-action@5651179950649c44da31d346537e20c0534f0f25
      with:
        tool: cargo-llvm-cov@0.4.5
    - name: Running tests with coverage
      run: make ci-test-coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574
      with:
        files: ci-coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}
        # Codecov is flaky and will randomly fail. We'd rather not have random failures on master.
        fail_ci_if_error: false
        verbose: true
